name: "Fetch Icons"
description: "Fetch icons from the ZDS Library"
inputs:
  figma-access-token:
    description: "The personal access token given by Figma. Required to make API calls"
    required: true
  date:
    description: "The date and time the action was run"
    required: true
  actions-runner-debug:
    description: "The date and time the action was run"
    required: false
    default: "false"
#    type: boolean
outputs:
  files_changed:
    description: "Array of files if any icons have been added or removed. If this length > 0, the PR should be created."
  comment:
    description: "The comment to be added to the PR"
runs:
  using: "node20"
  main: "index.js"
