name: "Fetch Icons"
description: "Fetch icons from the ZDS Library"
inputs:
  figma-access-token:
    description: "The personal access token given by Figma. Required to make API calls"
    required: true
  date:
    description: "The date and time the action was run"
    required: true
outputs:
  files_changed:
    description: "Boolean that gets set to true if any icons have been added or removed"
runs:
  using: "node20"
  main: "index.js"
