name: Build

on:
  workflow_dispatch:
  schedule:
    # Runs automatically twice a week on Monday and Wednesday
    - cron: "0 8 * * 1"
    - cron: "0 8 * * 3"

jobs:
  fetch_icons:
    runs-on: ubuntu-latest
    name: Fetch icons and build output files
    # Uncomment below line if testing action via push to prevent recursion
    if: ${{ github.event.commits[0].author.name != 'Automated Version Bump' }}
    outputs:
      update: ${{ steps.fetch_icons.outputs.files_changed }}
      version: ${{ steps.package-version-new.outputs.current-version }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.ref_name}}
          token: ${{ secrets.PAT }}
      - name: Install packages
        run: npm ci
      - name: Compile Typescript files
        run: tsc
      - name: Fetch icons
        id: "fetch_icons"
        uses: ./.github/fetch_icons
        with:
          figma-access-token: ${{ secrets.FIGMA_PERSONAL_ACCESS_TOKEN }}
      - name: "Icons changed"
        run: echo ${{ steps.fetch_icons.outputs.files_changed }}
      - name: Get current date
        if: ${{ steps.fetch_icons.outputs.files_changed  == 'true'}}
        id: date
        run: echo "::set-output name=date::$(date +'%d-%b-%Y')"
      - name: Update
        if: ${{ steps.fetch_icons.outputs.files_changed  == 'true'}}
        id: update
        run: |
          git config --global user.name "zeta-icons-bot"
          git config --global user.email "zeta-icons-bot@github.com"
          git checkout -b icon-updates
          git add -A
          git commit -m "ci: Icon updates ${{ steps.date.outputs.date }}"
          git push --set-upstream origin icon-updates
