name: Copy content to other repository

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      branch:
        required: true
        type: string
      source_dir:
        required: true
        type: string
      destination_dir:
        required: true
        type: string
      commit_msg:
        required: true
        type: string
      prerun:
        required: false
        type: string
      pr_body:
        required: true
        type: string
    secrets:
      PAT:
        required: true

jobs:
  copy_content:
    runs-on: ubuntu-latest
    steps:
      - name: Check if existing tokens branch exists
        id: check_branch
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: echo "branch_exists=$(gh api repos/${{ inputs.repo }}/branches/${{ inputs.branch }} --jq '.name' | wc -l | xargs)" >> $GITHUB_OUTPUT

      - name: Check if open PR exists
        id: check_pr
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: echo "pr_exists=$(gh pr list -R ${{ inputs.repo }} -H ${{ inputs.branch }} --json number -q length)" >> $GITHUB_OUTPUT

      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          path: "source"

      - name: Checkout destination repo (Branch exists)
        uses: actions/checkout@v4
        if: ${{ steps.check_branch.outputs.branch_exists != 0 }}
        with:
          path: "destination"
          repository: ${{ inputs.repo }}
          token: ${{ secrets.PAT }}
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Checkout destination repo (Branch doesn't exist)
        uses: actions/checkout@v4
        if: ${{ steps.check_branch.outputs.branch_exists == 0 }}
        with:
          path: "destination"
          repository: ${{ inputs.repo }}
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Create branch in destination repo
        if: ${{ steps.check_branch.outputs.branch_exists == 0 }}
        run: |
          cd destination
          git checkout -b ${{ inputs.branch }}

      - name: Run pre-run command
        if: inputs.prerun != ''
        run: |
          cd destination
          eval ${{ inputs.prerun }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%d %b %Y, %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Copy files
        run: cp -r source/${{ inputs.source_dir }}/* destination/${{ inputs.destination_dir }}

      - name: Stage / Push destination changes
        id: push_changes
        run: |
          cd destination
          git config --global user.name "zeta-icons-bot"
          git config --global user.email "zeta-icons-bot@github.com"
          git add -A
          if git diff --staged --quiet --exit-code; then
            echo "changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "changes=true" >> "$GITHUB_OUTPUT"
            git commit -m "deps(automated): ${{inputs.commit_msg}} ${{ steps.date.outputs.date }}"
            git push --set-upstream origin ${{inputs.branch}} -f
          fi

      - name: Build PR comment
        id: build_comment
        if: ${{ steps.push_changes.outputs.changes == 'true' }}
        run: |
          echo "comment<<EOF" >> "$GITHUB_OUTPUT"
          echo "<sub>Created by the Zeta icons bot 🤖 <br />Last updated: ${{ steps.date.outputs.date }}</sub><br />${{inputs.pr_body}} " >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Open PR
        uses: thecanadianroot/open-pull-request-action@v1.1.1
        if: ${{ steps.check_pr.outputs.pr_exists == 0  && steps.push_changes.outputs.changes == 'true' }}
        with:
          token: ${{ secrets.PAT }}
          base: main
          head: ${{ inputs.branch }}
          title: "deps(automated): ${{inputs.commit_msg}}"
          labels: tokens
          body: ${{ steps.build_comment.outputs.comment }}
          repository: ${{ inputs.repo }}

      - name: Add comment to existing PR
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        if: ${{ steps.check_pr.outputs.pr_exists != 0 && steps.push_changes.outputs.changes == 'true' }}
        run: gh pr edit -R ${{ inputs.repo }} ${{ inputs.branch }} --body "${{ steps.build_comment.outputs.comment }}"
