name: "fetch-icons"

on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    # Runs automatically twice a week on Monday and Wednesday
    - cron: "0 8 * * 1"
    - cron: "0 8 * * 3"

jobs:
  fetch_icons:
    runs-on: ubuntu-latest
    name: Fetch Icons
    # Uncomment below line if testing action via push to prevent recursion
    if: ${{( github.event_name != 'schedule' && github.event.commits[0].author.name != 'Automated Version Bump') ||  github.event_name == 'schedule' }}
    outputs:
      update: ${{ steps.fetch_icons.outputs.files_changed }}
      version: ${{ steps.package-version-new.outputs.current-version }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Install packages
        run: npm ci
      - name: Compile Typescript files
        run: tsc
      - name: Fetch icons
        id: "fetch_icons"
        uses: ./.github/fetch_icons
        with:
          figma-access-token: ${{ secrets.FIGMA_PERSONAL_ACCESS_TOKEN }}
      - name: "Files changed"
        run: echo ${{ steps.fetch_icons.outputs.files_changed }}
      - name: "Bump Version"
        uses: "phips28/gh-action-bump-version@master"
        if: ${{ steps.fetch_icons.outputs.files_changed  == 'true'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default: patch
          skip-commit: "true"
          skip-tag: "true"
          skip-push: "true"
      - name: Get new package version
        id: package-version-new
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Update
        if: ${{ steps.fetch_icons.outputs.files_changed  == 'true'}}
        id: update
        run: |
          git config --global user.name "zeta-icons-bot"
          git config --global user.email "zeta-icons-bot@github.com"
          git add -A
          git tag ${{ steps.package-version-new.outputs.current-version }}
          git commit -m "Version ${{ steps.package-version-new.outputs.current-version }}" --no-edit
          git push -f
          git push -f --tags
          echo "newSha=$(git rev-parse origin/main)" >>  $GITHUB_ENV
      - name: Publish to NPM
        if: ${{ steps.fetch_icons.outputs.files_changed  == 'true'}}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  zeta_web:
    name: Update Zeta Web
    needs: fetch_icons
    runs-on: ubuntu-latest
    if: ${{ needs.fetch_icons.outputs.update == 'true' }}
    steps:
      - name: "Trigger repository_dispatch in zeta-web"
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/zebratechnologies/zeta-web/dispatches \
            -d '{"event_type":"update-icons","client_payload":{"version": "${{ needs.fetch_icons.outputs.version }}"}'

  website:
    name: Update the Zeta Icons website
    needs: fetch_icons
    runs-on: ubuntu-latest
    if: ${{ needs.fetch_icons.outputs.update == 'true' }}
    steps:
      - name: "Trigger repository_dispatch in zeta-web"
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/zebratechnologies/zeta-icons-website/dispatches \
            -d '{"event_type":"update-icons","client_payload":{"version": "${{ needs.fetch_icons.outputs.version }}"}'

  zeta_flutter_PR:
    needs: fetch_icons
    runs-on: ubuntu-latest
    if: ${{ needs.fetch_icons.outputs.update == 'true' }}
    name: Commit and raise PR in Zeta Flutter
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Push dart file to Zeta Flutter
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source_file: "./build_files/icons.dart"
          destination_repo: "ZebraDevs/zeta_flutter"
          destination_folder: "lib/src/assets"
          destination_branch_create: "icons/${{ needs.fetch_icons.outputs.version }}"
          user_email: "zeta-icons-bot@github.com"
          user_name: "zeta-icons-bot"
          commit_message: "icons.dart"
      - name: Push round icon font file to Zeta Flutter
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source_file: "./fonts/zeta-icons-round.ttf"
          destination_repo: "ZebraDevs/zeta_flutter"
          destination_folder: "lib/src/assets/fonts"
          destination_branch: "icons/${{ needs.fetch_icons.outputs.version }}"
          user_email: "zeta-icons-bot@github.com"
          user_name: "zeta-icons-bot"
          commit_message: "rounded font file"
      - name: Push sharp icon font file to Zeta Flutter
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source_file: "./fonts/zeta-icons-sharp.ttf"
          destination_repo: "ZebraDevs/zeta_flutter"
          destination_folder: "lib/src/assets/fonts"
          destination_branch: "icons/${{ needs.fetch_icons.outputs.version }}"
          user_email: "zeta-icons-bot@github.com"
          user_name: "zeta-icons-bot"
          commit_message: "sharp font file"

      #TODO close previous PRs, delete branch with previous version number
      - name: Open Zeta Flutter PR
        uses: thecanadianroot/open-pull-request-action@v1.1.1
        with:
          token: ${{ secrets.PAT }}
          base: main
          head: "icons/${{ needs.fetch_icons.outputs.version }}"
          title: "icons/${{ needs.fetch_icons.outputs.version }}"
          labels: icons
          owner: zebratechnologies
          repository: ZebraDevs/zeta_flutter
