name: CI - On Main

on:
  push:
    branches:
      - main
      - UX-1462

permissions:
  contents: write

jobs:
  on-develop:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[released]')"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # token: ${{secrets.PAT}}

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Check if icons have updated
        id: check-icons
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q '^outputs/'; then
            echo "icons_changed=true" >> $GITHUB_OUTPUT
          else
            echo "icons_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if icons have not changed
        if: steps.check-icons.outputs.icons_changed == 'false'
        run: |
          echo "No icon changes detected. Skipping workflow."
          exit 0
      # TODO: Do regular release please?
      - name: Run release script
        run: bash scripts/ci/changelog.sh

      - name: Get version from package.json
        id: get-version
        run: |
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Read changelog message
        id: changelog_msg
        run: |
          {
            echo 'msg<<EOF'
            cat cmt_msg.tmp
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Push changes
        run: |
          git config --global user.name "zeta-icons-bot"
          git config --global user.email "zeta-icons-bot@github.com"
          git add package.json CHANGELOG.md
          git commit --amend -m "$(git log -1 --pretty=%B) [released]"
          git tag -f zeta-icons-v${{ env.VERSION }} -m '${{steps.changelog_msg.outputs.msg}}'
          git push origin UX-1462 --force-with-lease
          git push --tags

      - uses: actions/github-script@v7
        name: Create release
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `zeta-icons-v${{ env.VERSION }}`,
              body: `${{steps.changelog_msg.outputs.msg}}`
            })
