name: CI - On Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  get_changed_icons:
    name: Get changed icons
    runs-on: ubuntu-latest
    outputs:
      BODY: ${{ steps.get-changed-icons.outputs.body }}
      conventional-commit: ${{ steps.get-changed-icons.outputs.conventional-commit }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: yarn install --immutable
      - run: yarn run build
      - name: Get changed icons
        id: get-changed-icons
        uses: ./.github/get_changed_icons

  update_flutter:
    needs: get_changed_icons
    uses: ./.github/workflows/update_zeta_flutter.yml
    secrets: inherit
    with:
      comment: "${{ needs.get_changed_icons.outputs.BODY}} ${{ needs.get_changed_icons.outputs.conventional-commit}}"

  update_android:
    needs: get_changed_icons
    uses: ./.github/workflows/update_zds_android.yml
    secrets: inherit
    with:
      comment: "${{ needs.get_changed_icons.outputs.BODY}} ${{ needs.get_changed_icons.outputs.conventional-commit}}"
