name: CI - On Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref_name}}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - name: Install packages
        run: npm ci
      - name: Compile Typescript files
        run: tsc
      - name: Dry run
        run: npx figma connect publish --dry-run --token ${{ secrets.FIGMA_PERSONAL_ACCESS_TOKEN}}
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish_code_connect:
    uses: ./.github/workflows/publish_code_connect.yml
    if: always()
    secrets: inherit

  update_npm_dependencies:
    uses: ./.github/workflows/update_dependencies.yml
    secrets: inherit

  update_flutter:
    uses: ./.github/workflows/update_zeta_flutter.yml
    secrets: inherit

  update_android:
    uses: ./.github/workflows/update_zds_android.yml
    secrets: inherit
