name: Publish

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      PAT:
        required: true
      NPM_TOKEN:
        required: true

jobs:
  publish_npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
