name: Publish to NPM

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Inject auth token
        run: |
          echo npmAuthToken: "${{secrets.NPM_TOKEN}}" >> ./.yarnrc.yml

      - name: Install packages
        run: yarn install --immutable

      - name: Compile Typescript files
        run: tsc

      - name: Publish
        run: yarn npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
