name: CI - On Main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ github.token }}
          config-file: .release-please/release-please-config.json
          manifest-file: .release-please/.release-please-manifest.json
