name: Update zeta-icons-website

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: "Version to update to"
        required: true
    secrets:
      PAT:
        required: true

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'zebratechnologies',
              repo: 'design.zebra.com',
              workflow_id: 'deploy.yml',
              ref: 'main', 
              inputs:{
                package_to_update: 'icons',
              }
            })
