name: Update zeta_flutter

on:
  workflow_call:
    inputs:
      changelog:
        description: "Changelog for the icons update"
        required: true
        type: string
      version:
        description: "Version number for the icons update"
        required: true
        type: string
    secrets:
      PAT:
        description: "Personal Access Token for GitHub"
        required: true

jobs:
  zeta_flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger zeta_flutter/fetch_icons script
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'ZebraDevs',
              repo: 'zeta_flutter',
              workflow_id: 'fetch-icons.yml',
              ref: 'main',
              inputs: {
                changelog: `${{ inputs.changelog }}`,
                version: `${{ inputs.version }}`
              }
            })
