name: Update dependencies (zeta-web, zeta-icons-website)

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:
  get_version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.current-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref_name}}
      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
  zeta_web:
    name: Update Zeta Web
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - name: "Trigger repository_dispatch in zeta-web"
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/zebratechnologies/zeta-web/dispatches \
            -d '{"event_type":"update-icons","client_payload":{"version": "${{ needs.get_version.outputs.version }}"}'
  website:
    name: Update the Zeta Icons website
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - name: "Trigger repository_dispatch in zeta-icons-website"
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/zebratechnologies/zeta-icons-website/dispatches \
            -d '{"event_type":"update-icons","client_payload":{"version": "${{ needs.get_version.outputs.version }}"}'
