name: Update zeta_flutter

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      PAT:
        required: true
      comment:
        required: true

env:
  flutter_branch: update-zeta-icons

jobs:
  publish_flutter:
    uses: ./.github/workflows/copy-content.yml
    secrets: inherit
    with:
      repo: ZebraDevs/zeta_flutter
      branch: "update-zeta-icons"
      source_dir: "./outputs/flutter/."
      destination_dir: "packages/zeta_icons/lib/src"
      commit_msg: "Update icons"
      pr_body: ${{inputs.comment}}
