name: Update zeta_flutter

on: workflow_call

jobs:
  get_version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.current-version }}
    steps:
      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
  publish_flutter:
    runs-on: ubuntu-latest
    name: Commit and raise PR in Zeta Flutter
    needs: get_version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push dart file to Zeta Flutter
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          #TODO: pass file paths as inputs
          source_file: "./outputs/definitions/icons.dart"
          destination_repo: "ZebraDevs/zeta_flutter"
          destination_folder: "lib/src/assets"
          destination_branch_create: "icons/${{ needs.get_version.outputs.version }}"
          user_email: "zeta-icons-bot@github.com"
          user_name: "zeta-icons-bot"
          commit_message: "icons.dart"
      - name: Push round icon font file to Zeta Flutter
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source_file: "./outputs/font/zeta-icons-round.ttf"
          destination_repo: "ZebraDevs/zeta_flutter"
          destination_folder: "lib/src/assets/fonts"
          destination_branch: "icons/${{ needs.get_version.outputs.version }}"
          user_email: "zeta-icons-bot@github.com"
          user_name: "zeta-icons-bot"
          commit_message: "rounded font file"
      - name: Push sharp icon font file to Zeta Flutter
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source_file: "./outputs/font/zeta-icons-sharp.ttf"
          destination_repo: "ZebraDevs/zeta_flutter"
          destination_folder: "lib/src/assets/fonts"
          destination_branch: "icons/${{ needs.get_version.outputs.version }}"
          user_email: "zeta-icons-bot@github.com"
          user_name: "zeta-icons-bot"
          commit_message: "sharp font file"

      #TODO close previous PRs, delete branch with previous version number
      - name: Open Zeta Flutter PR
        uses: thecanadianroot/open-pull-request-action@v1.1.1
        with:
          token: ${{ secrets.PAT }}
          base: main
          head: "icons/${{ needs.fetch_icons.outputs.version }}"
          title: "icons/${{ needs.fetch_icons.outputs.version }}"
          labels: icons
          owner: zebratechnologies
          repository: ZebraDevs/zeta_flutter
