name: Update zds_android

on:
  workflow_call:
    inputs:
      changelog:
        description: "Changelog for the icons update"
        required: true
        type: string
    secrets:
      PAT:
        description: "Personal Access Token for GitHub"
        required: true

jobs:
  publish_android:
    uses: ./.github/workflows/copy-content.yml
    secrets:
      PAT: ${{ secrets.PAT }}
    with:
      repo: ZebraDevs/zds-android
      branch: "main"
      source_dir: "outputs/android"
      destination_dir: "components/src/main/res/drawable"
      commit_msg: "${{inputs.changelog}}"
      prerun: rm -f components/src/main/res/drawable/ic_*.xml
